name: CI-CD (Dev)

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x64
          cache: 'gradle'

      - name: Build & Test
        run: |
          echo "${{ secrets.DEV_DB_PROPERTIES }}" > src/main/resources/secret.properties
          echo "${{ secrets.JWT_PROPERTIES }}" > src/main/java/app/learningtrip/apiserver/configuration/auth/jwt/JwtProperties.java
          echo "${{ secrets.API_KEY_PROPERTIES }}" > src/main/resources/application-API-KEY.properties
          ./gradlew build --no-daemon

      - name: Kill Server process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd development
            sudo ./kill.sh
            sudo rm `ls | grep .jar | awk '{print $1}'`
            exit

      - name: Send Jar file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "build/libs/api-server-0.0.1-SNAPSHOT.jar"
          target: "~/development"
          strip_components: 2

      - name: Run Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd development
            mv `ls | grep .jar | awk '{print $1}'` lt-dev.jar
            nohup java -jar lt-dev.jar > nohup.out 2>&1 &
            exit
      
