name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        architecture: x64
        cache: 'gradle'
        
    - name: Build & Test
      run: |
        ./gradlew build --no-daemon
        sudo chmod -R 777 build
        
    - name: Kill Server process
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sudo ./kill.sh
          sudo rm `ls | grep .jar | awk '{print $1}'`
          exit
    
    - name: Send Jar file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "build/libs/api-server-0.0.1-SNAPSHOT.jar"
        target: "/"
        strip_components: 2
    
    - name: Run Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          nohup java -jar `ls | grep .jar | awk '{print $1}'` > nohup.out 2>&1 &
          exit
      
